Add window restore icon
Zagrios/bs-manager pull request #562
Opened 2024-08-17 16:09 UTC by joriskleiber

## Scope

Adds an window restore icon and displays it when the window is maximized.

## Emoji Guide

**For reviewers: Emojis can be added to comments to call out blocking versus non-blocking feedback.**

E.g: Praise, minor suggestions, or clarifying questions that don’t block merging the PR.

> 🟢 Nice refactor!

> 🟡 Why was the default value removed?

E.g: Blocking feedback must be addressed before merging.

> 🔴 This change will break something important

|              |                |                                     |
| ------------ | -------------- | ----------------------------------- |
| Blocking     | 🔴 ❌ 🚨       | RED                                 |
| Non-blocking | 🟡 💡 🤔 💭    | Yellow, thinking, etc               |
| Praise       | 🟢 💚 😍 👍 🙌 | Green, hearts, positive emojis, etc |

2024-08-18 22:07 UTC, joriskleiber commented
This fails because I corrected the spelling of the `onClick` function. Maybe you could give me some pointers how to fix this?

2024-08-19 18:06 UTC, Zagrios commented
@joriskleiber it's a new rule of sonarlint
now when you want to use `onClick` you must be use it with an interactive element such as `button`
Just change all divs using "onClick" by buttons and it sould be good 😉

2024-08-19 18:08 UTC, Zagrios requested changes

2024-08-19 18:08 UTC, Zagrios commented on src/renderer/components/title-bar/title-bar.component.tsx
> +                    <div onClick={toggleMaximize} className="text-gray-800 dark:text-gray-200 hover:bg-gray-300 dark:hover:bg-[#4F545C] cursor-pointer w-11 h-full shrink-0 flex justify-center items-c
```suggestion
                    <button onClick={toggleMaximize} className="text-gray-800 dark:text-gray-200 hover:bg-gray-300 dark:hover:bg-[#4F545C] cursor-pointer w-11 h-full shrink-0 flex justify-center items-center" id="max-button">
```

2024-08-19 18:08 UTC, Zagrios commented on src/renderer/components/title-bar/title-bar.component.tsx
>                      </div>
```suggestion
                    </button>
```

do that for all div using "onClick" and it will be good 👍

2024-08-19 18:35 UTC, Zagrios approved these changes
nice! 🙌

2024-08-19 18:35 UTC, merged