[feat-216] support for sorting maps/songs
Zagrios/bs-manager pull request #601
Opened 2024-10-02 13:48 UTC by silentrald

Closes #216

_**UI subject to change**_
![image](https://github.com/user-attachments/assets/c0b746b4-8589-479e-94a5-ded7b212a9d3)

2025-01-07 19:03 UTC, Zagrios requested changes

2025-01-07 19:03 UTC, Zagrios commented on src/renderer/services/playlists/sorter.service.ts
> +export class PlaylistsSorterService {
You can even create an abstract class for these two 🤔
In the future, it's possible we might want to sort other types of content (models, etc, who knows), and we could create another Sorter class extending the abstract class 🤷

2025-01-09 16:09 UTC, silentrald commented on src/renderer/services/playlists/sorter.service.ts
> +export class PlaylistsSorterService {
Was thinking along the lines of just of using a default sorter class since the two classes literally just share the same logic, just different variable values. The class can still be extended if we need any special thing for the sorter to do in any case.

2025-01-11 11:52 UTC, Zagrios approved these changes
Looks good to me 🙌

2025-01-11 11:59 UTC, Zagrios commented
Thanks @silentrald ! ❤️ 
Merging 🚀

2025-01-11 11:59 UTC, merged