[Translation] Add Italian translation
Zagrios/bs-manager pull request #721
Opened 2024-12-29 23:12 UTC by Davitekk

Everything works but i have the same problem with making a rounded flag.
I took as reference the changes that [izuna_1](https://github.com/izunya) did to the code -> [Pull Request For Reference](https://github.com/Zagrios/bs-manager/pull/641)

![The Flag Problem](https://github.com/user-attachments/assets/23acfc0d-0e3b-4bb8-ac46-093f1230261b)

### Other Screenshots of how it turned out:

![Screenshot 1](https://github.com/user-attachments/assets/9bc43ea4-e4d8-4fd9-9ec7-b58024247e5b)
![Screenshot 2](https://github.com/user-attachments/assets/23b7f36b-28f6-49aa-97b5-7a45f2d2a321)

2025-01-02 01:25 UTC, Zagrios commented
@Davitekk you can use this for the flag :
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 71 48" ref={ref} {...props} width="71" height="48">
            <g fill="none">
                <path d="M6.65.53A6.36 6.36 0 0 0 .29 6.89v34.27a6.36 6.36 0 0 0 6.36 6.36h17v-47z" fill="#57A863"/>
                <path d="M23.63.53v47H47v-47z" fill="#FFF"/>
                <path d="M63.92.53H47v47h16.92a6.36 6.36 0 0 0 6.36-6.36V6.89A6.36 6.36 0 0 0 63.92.53" fill="#ED5565"/>
            </g>
</svg>
```

2025-01-02 01:29 UTC, Zagrios requested changes
Some translations are missing @Davitekk

2025-01-02 01:29 UTC, Zagrios commented on assets/jsons/translations/it.json
> +                    "ko-KR": "한국어",
the translation for "it-IT" is missing, should be `Italiano`
![image](https://github.com/user-attachments/assets/b27aff48-aed6-41f0-9ddc-6a3fcc33f21e)

2025-01-02 01:29 UTC, Zagrios commented on assets/jsons/translations/it.json
> +                        "ko-KR": "Coreano"
the translation for "it-IT" is missing, should be `Italiano`
![image](https://github.com/user-attachments/assets/b27aff48-aed6-41f0-9ddc-6a3fcc33f21e)

2025-01-02 01:29 UTC, Zagrios commented on assets/jsons/translations/it.json
> +            "Easy": "Easy",
This has not been translated, is it intended ?

2025-01-02 09:52 UTC, Davitekk commented on assets/jsons/translations/it.json
> +            "Easy": "Easy",
Thought it looked better without translation, changed my mind.

2025-01-02 11:45 UTC, Davitekk commented
Everything should be resolved.

2025-01-02 15:54 UTC, Zagrios requested changes
Some translations are missing

2025-01-02 15:54 UTC, Zagrios commented on assets/jsons/translations/it.json
> +        },
`"map-leaderboard"` translations are missing here
![image](https://github.com/user-attachments/assets/41283c1a-74cd-4b53-ac9e-b94066fcd2e8)

2025-01-02 15:54 UTC, Zagrios commented on assets/jsons/translations/it.json
> +            "exclude": "escludi"
The `"leaderboard"` translation is missing here

2025-01-02 16:10 UTC, Davitekk commented
Resolved.

2025-01-03 00:20 UTC, Zagrios approved these changes
Everything looks good to me 🙌

2025-01-03 00:20 UTC, Zagrios commented
Thanks a lot @Davitekk ! ❤️ 
Merging 🚀

2025-01-03 00:21 UTC, merged